//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start,End,Event Name,Waypoint Link
        ///07:00,07:15,Tequatl the Sunless,[&amp;BNABAAA=]
        ///11:30,11:45,Tequatl the Sunless,[&amp;BNABAAA=]
        ///16:00,16:15,Tequatl the Sunless,[&amp;BNABAAA=]
        ///19:00,19:15,Tequatl the Sunless,[&amp;BNABAAA=]
        ///00:00,00:15,Tequatl the Sunless,[&amp;BNABAAA=]
        ///03:00,03:15,Tequatl the Sunless,[&amp;BNABAAA=]
        ///08:00,08:15,Triple Wurm,[&amp;BKoBAAA=]
        ///12:30,12:45,Triple Wurm,[&amp;BKoBAAA=]
        ///17:00,17:15,Triple Wurm,[&amp;BKoBAAA=]
        ///20:00,20:15,Triple Wurm,[&amp;BKoBAAA=]
        ///01:00,01:15,Triple Wurm,[&amp;BKoBAAA=]
        ///04:00,04:15,Triple Wu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bosses {
            get {
                return ResourceManager.GetString("bosses", resourceCulture);
            }
        }
    }
}
